In [7]:
import matplotlib.pyplot as plt
import numpy as np

In [101]:
X_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

node_indices = [i for i in range(X_train.shape[0])]


In [102]:
X_train.shape[0]

10

In [123]:
def entropy(y):
    entropy = 0
    if len(y)!=0:
        ones = y[y==1]
        p1 = len(ones)/len(y)
        print(p1)
        if p1!=0 and p1!=1:
            entropy = -(p1*np.log2(p1)+(1-p1)*np.log2(1-p1))
        else:
            entropy = 0

        #print(f'Entropy is {entropy}') Just for seing entropy value
    return entropy

In [104]:
print(entropy(y_train))

0.5
Entropy is 1.0
1.0


In [154]:
def split_dataset(X,node_indices,feature):
    
    left_indices = []
    right_indices = []
    for i in node_indices: #Remember range is exclusive ;so we need to add one step in our loop
        if X[i][feature] == 0:
            left_indices.append(i)
        else:
            right_indices.append(i)
            
    return left_indices,right_indices

In [155]:
feature = 0
left_split,right_split = split_dataset(X_train,node_indices,feature)

In [156]:
print(left_split,right_split )
print(X_train[left_split])

[5, 6, 8] [0, 1, 2, 3, 4, 7, 9]
[[0 1 1]
 [0 0 0]
 [0 1 0]]


In [148]:
def information_gain(X,y,node_indices,feature):
    #We split the data 
    left_split,right_split = split_dataset(X_train,node_indices,feature)

    
    X_node,y_node   = X[node_indices],y[node_indices]
    X_left,y_left   = X[left_split],y[left_split]
    X_right,y_right = X[right_split],y[right_split]

    w_left,w_right = len(X_left)/ len(X_node) , len(X_right) / len(X_node)

    H_node = entropy(y_node)
    H_left = entropy(y_left)
    H_right = entropy(y_right)

    info_gain = H_node - (w_left * H_left + w_right * H_right)
    return info_gain

In [149]:
info_gain = information_gain(X_train,y_train,node_indices,feature)

0.5
0.3333333333333333
0.5714285714285714


In [163]:
def best_split(X,y,node_indices):
    feature_set = X.shape[1]
    best_feature = -1
    
    max_information_gain = 0
    info = 0
    #print(information_gain(X,y,node_indices,0))
    for feature in range(feature_set):
        #print(f'Round {feature}')
        
        info_gain_potential = information_gain(X_train,y_train,node_indices,feature)
        
        #print(f'Info_gain: {info_gain_potential}')
        if info_gain_potential > max_information_gain :
            max_information_gain = info_gain_potential
            best_feature = feature

    return best_feature

In [165]:
best_feature = best_split(X_train,y_train,node_indices)

0.5
0.3333333333333333
0.5714285714285714
0.5
0.3333333333333333
0.75
0.5
0.2
0.8


In [166]:
print(best_feature)

2


In [176]:
tree = []
def build_tree(X,y,node_indices,branch_name,max_depth,current_depth):
    if current_depth == max_depth: # When we are in the maximum depth ,we stop
        print('Max tree has been reached')
        return

    best_feature = best_split(X,y,node_indices) # We search the best feature for spliting data

    left_indices,right_indices = split_dataset(X,node_indices,best_feature)
    tree.append((left_indices,right_indices,best_feature))

    build_tree(X,y,left_indices,'Left',max_depth,current_depth+1) # We build the left side of the tree
    build_tree(X,y,right_indices,'Right',max_depth,current_depth+1) # We build the right side of the tree



In [177]:
build_tree(X_train,y_train,node_indices,'Node',max_depth=2,current_depth=0)


0.5
0.3333333333333333
0.5714285714285714
0.5
0.3333333333333333
0.75
0.5
0.2
0.8
0.2
0.5
0.0
0.2
0.0
1.0
0.2
0.2
Max tree has been reached
Max tree has been reached
0.8
0.0
1.0
0.8
1.0
0.6666666666666666
0.8
0.8
Max tree has been reached
Max tree has been reached


In [178]:
tree

[([2, 3, 6, 8, 9], [0, 1, 4, 5, 7], 2),
 ([2, 3, 6, 9], [8], 1),
 ([5], [0, 1, 4, 7], 0)]